name: Release

on:
  push:
    branches: [master]
    paths:
    tags:
      - v*
  release:
    types: [created]

env:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      steps:
        - run: "! [[ $GITHUB_REF =~ -release$ ]]"
        - run: "! [[ ${GITHUB_REF:10} =~ ^v[0-9]+$ ]]"
  debug:
    runs-on:
    steps:
  build:
  deploy:
    runs-on: ubuntu-latest
    steps:
  release:
    name: Publish Release
    needs: validate
    uses: actions/checkout@v2
    id: create_release
    runs-on: ubuntu-latest
    steps:
