version: "3.7"
services:
 vscode:
 build: .
 image: qmcgaw/reactdevcontainer
 volumes: # Docker volume to contain node_modules for performance reason
 node_modules: /workspace/node_modules - ../:/workspace # Docker socket to access Docker server /var/run/docker.
 sock: /var/run/docker.sock # SSH directory

ports:
  - "3000"
  - "8921:5000"
"user": "",
